### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by Altoholic** [leatrix/leatrix-maps-classic#1]
2x [ADDON_ACTION_FORBIDDEN] AddOn 'Leatrix_Maps' tried to call the protected function 'AcceptBattlefieldPort()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `AcceptBattlefieldPort'
FrameXML\StaticPopup.lua:689: in function `OnAccept'
FrameXML\StaticPopup.lua:5002: in function `StaticPopup_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

**Comment by leatrix** [comment]
When do you see this?  Is it reproducible?  If you disable other addons, does the error occur again?

**Comment by Altoholic** [comment]
when i click the BG popup to accept to go to the BG, that error 100% occur. And i can't enter the BG, i have to right click the BG minimap icon to accept.

**Comment by leatrix** [comment]
It works fine for me.  Disable all other addons except Leatrix Maps.  The problem should be fixed.  Enable other addons gradually until you find the addon causing the problem.
