### ISSUE TITLE
request

### ISSUE THREAD

**Issue by WoWEye** [leatrix/leatrix-maps-classic#10]
I play both TBC and Classic Era. Is it possible to make the Enlarge Player Arrow go beyond 200% ... say 400% ? I play mostly with my map scaled down and it's very hard to see where I am on the map.

**Comment by leatrix** [comment]
Added to latest alpha releases for Classic Era, BCC and Shadowlands.

For Classic Era and BCC:
- Player arrow and group icon maximum size (for both world map and battlefield map) and battlefield maximum size increased to 400%.

https://www.curseforge.com/wow/addons/leatrix-maps-classic/files/all
https://www.curseforge.com/wow/addons/leatrix-maps-bcc/files/all

For Shadowlands:
- Player arrow and group icon maximum size (for battlefield map) and battlefield maximum size increased to 400%.

https://www.curseforge.com/wow/addons/leatrix-maps/files/all
