### ISSUE TITLE
Player Arrow missing

### ISSUE THREAD

**Issue by Cwis3man** [leatrix/leatrix-maps-classic#12]
I have reinstalled the addon and deleted WTF several times. When entering the world the 'm' hotkey does not work until I do /ltm and click 'Reset Map Layout' Player arrow still does not show. Cursor Coords do not seem to work either.

**Comment by leatrix** [comment]
Disable all other addons.  Try again.  Report back when you have done that.

**Comment by Cwis3man** [comment]
It was the latest update to move and improve.

Do you have anything that will move the buff frame? 

https://www.curseforge.com/wow/addons/move-and-improve

**Comment by leatrix** [comment]
Install Leatrix Plus.
Enter '/ltp' to open it.
Enable 'Manage buffs' ('Frames menu').
After the reload, click the little configuration button next to 'Manage buffs' and you can now drag and scale the buffs frame as you wish.

Leatrix Plus is completely modular so it will only do what you tell it to do.  There are a lot of settings but if you don't enable them, they won't do anything so if you want to use it just to move the buffs frame, you can do that.  But while it's installed, you might want to browse the other settings as there are probably other things you will like.
https://www.curseforge.com/wow/addons/leatrix-plus-classic

**Comment by leatrix** [comment]
https://github.com/leatrix/leatrix-maps-bcc/issues/45

**Comment by leatrix** [comment]
Looks like the new MAI update (2021.12.04-18:45) fixed the problem with the map opening so the MAI fix has been removed from LTM 1.14.11.alpha.8 (as well as the latest BCC alpha).  That said, if you use MAI to move frames, you might have problems dragging the world map frame to where you want it to be.
