### ISSUE TITLE
Show points of interest

### ISSUE THREAD

**Issue by paroyer** [leatrix/leatrix-maps-classic#2]
For some reason no matter if Show points of interest is tick or not, I seem to always have the flightmaster pins. Only the one for flight master, dungeon, raids, boat zeppelins and such are properly hidden. I dont have any lua error with this, just cant seem to be able to remove them, I use Handy Notes for such pins so i end up with 2 at each location. I could turn off handy notes flight master, but I'm using mostly all Handy Notes pins would better suit my style :3

**Comment by leatrix** [comment]
Another addon is showing the flight points.  Disable all addons except Leatrix Maps.  You should find that the flight points are not shown (as long as 'Show points of interest' or 'Show flight points' are unchecked).  Enable other addons gradually until you find the addon showing the flight points.
