### ISSUE TITLE
Map resize is reset each time the game is closed

### ISSUE THREAD

**Issue by alrick** [leatrix/leatrix-maps-classic#3]
Everytime I log back into my account the size of the map has been reset.
Anyway I can fix it ?

Thanks

**Comment by leatrix** [comment]
Another addon is probably changing the map scale.  Disable other addons, it should work fine.  Enable other addons gradually until you find the addon that's changing the map scale.

**Comment by alrick** [comment]
Yes it was another addon conflicting, thanks for your help !
