### ISSUE TITLE
The map won't close

### ISSUE THREAD

**Issue by Sommershade** [leatrix/leatrix-maps-classic#4]
I have two accounts and the map would not close on my second account (the last account I had opened). I had to disable it to get it close. 
I also use ElvUI.

**Comment by leatrix** [comment]
What happens with only LTM enabled on both accounts (all other addons disabled)?  Does it work?

**Comment by Sommershade** [comment]
I was about to come back and let you know I got it fixed. And really it is not LTM, it was ElvUI. I had to go through each addon to figure it out. I had dual monitor settings on the second account, but not on the first account. So when I enacted with the second screen, ElvUI did not like that. It was only until I went through each of the settings to verify I had them the same that I realized I had not turned on the dual monitor setting. Once I did so, the issue cleared up that was affecting LTM.

**Comment by leatrix** [comment]
Thank you for the update.
