### ISSUE TITLE
classic tbc issue: wrong version

### ISSUE THREAD

**Issue by taburetkin** [leatrix/leatrix-maps-classic#5]
leatrix v 1.13.106 does not start on classic tbc (v20501)
and there is a message in chat: wrong version installed!

i suppose current version of leatrix does not support client 20501 ?
do you have any plans to compile addon for classic tbc?

**Comment by leatrix** [comment]
Yes, Leatrix addons support Shadowlands, Wow Classic and Burning Crusade Classic.

Here are the links for BCC:
https://www.curseforge.com/wow/addons/leatrix-maps-bcc
https://www.curseforge.com/wow/addons/leatrix-plus-bcc
https://www.curseforge.com/wow/addons/leatrix-sounds-bcc

You may not find BCC versions of the addons in CurseForge App at the moment as there is currently an issue with it which CurseForge are looking into.

**Comment by leatrix** [comment]
Just to add to this.  As of yesterday, Leatrix addons for BCC are now available in CurseForge App.
